In [1]:
import pandas as pd

In [2]:
dataset = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

In [3]:
df = pd.read_csv(dataset)

In [4]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
type(df['Name'])

pandas.Series

In [21]:
type(df)

pandas.DataFrame

In [ ]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [10]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [10]:
df.shape

(891, 12)

In [11]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
df[((df['Sex'] == 'female') & (df['Survived'] == 1))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [26]:
s1 = [1,2,3,4,5,6,7,8,9,10]

In [27]:
type(s1)

list

In [31]:
s2 = pd.Series(s1, index= [1,2,3,4,5,6,7,8,9,10])
print(s2)

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [17]:
type(df.loc[0]['Age'])

numpy.float64

In [19]:
df.loc[0]['Name']

'Braund, Mr. Owen Harris'

In [18]:
df.loc[0, 'Name']

'Braund, Mr. Owen Harris'

In [23]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [83]:
df.iloc[1:3][['Name','Age','Survived']]

                                                Name   Age  Survived
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1

In [82]:
(df[['Sex','Survived']])

        Sex  Survived
0      male         0
1    female         1
2    female         1
3    female         1
4      male         0
..      ...       ...
886    male         0
887  female         1
888  female         0
889    male         1
890    male         0

[891 rows x 2 columns]

In [81]:
df[((df['Sex'] == 'female') & (df['Survived'] == 1))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [42]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [43]:
df.iloc[0:4, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
Name: Name, dtype: str

In [50]:
df.iloc[:4, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
Name: Name, dtype: str

In [55]:
df[(df['Age'] > 70)]['Name']

96                Goldschmidt, Mr. George B
116                    Connors, Mr. Patrick
493                 Artagaveytia, Mr. Ramon
630    Barkworth, Mr. Algernon Henry Wilson
851                     Svensson, Mr. Johan
Name: Name, dtype: str

In [68]:
dataframe = df[((df['Age'] > 70) & (df['Survived'] == 1))][['Name','Age', 'Sex']]

In [69]:
display(dataframe
        )

                                     Name   Age   Sex
630  Barkworth, Mr. Algernon Henry Wilson  80.0  male

In [75]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 630 to 630
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    1 non-null      str
 1   Age     1 non-null      float64
 2   Sex     1 non-null      str
dtypes: float64(1), str(2)
memory usage: 156.0 bytes

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [85]:
display(df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name', 'Age']])

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [87]:
df[0:4][['Name', 'Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0

In [101]:
df.iloc[0:3, 2]

0    3
1    1
2    3
Name: Pclass, dtype: int64

In [102]:
df.loc[:3, ['Survived', 'Name']]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [103]:
df.iloc[:3, [3,1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [104]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [107]:
df_by_PassengerId= df.set_index('PassengerId')

In [108]:
df_by_PassengerId.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [109]:
df_by_PassengerId.iloc[0]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [ ]:
display(df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name', 'Age']])

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [ ]:
df_by_PassengerId.loc[0]

KeyError: 0

In [112]:
df_by_PassengerId.reset_index()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [113]:
df_by_PassengerId

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [117]:
df_by_PassengerId = df_by_PassengerId.reset_index()

In [118]:
df_by_PassengerId.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
source_a = pd.DataFrame({'Months' : ['Jan','Feb','March'],
                         'Sales': [200,400, 300]})

In [4]:
display(source_a)

  Months  Sales
0    Jan    200
1    Feb    400
2  March    300

In [7]:
source_b = pd.DataFrame({'Months' : ['Jan','March'],
                         'Sales': [200, 300]})

In [8]:
display(source_b)

  Months  Sales
0    Jan    200
1  March    300

In [9]:
source_a + source_b

     Months  Sales
0    JanJan  400.0
1  FebMarch  700.0
2       NaN    NaN

In [10]:
sales_jan = pd.DataFrame({'sales' : [200,400, 300]}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         sales
Store_A    200
Store_B    400
Store_C    300

In [31]:
sales_feb = pd.DataFrame({'sales' : [400, 600]}, index=['Store_A',  'Store_C'])

sales_feb

         sales
Store_A    400
Store_C    600

In [12]:
sales_jan + sales_feb

         sales
Store_A  600.0
Store_B    NaN
Store_C  900.0

In [13]:
common_index = sales_jan.index

common_index

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [15]:
sales_feb_aligned = sales_feb.reindex(common_index)

sales_feb_aligned

         sales
Store_A  400.0
Store_B    NaN
Store_C  600.0

In [19]:
diff_sales = sales_feb_aligned['sales'] - sales_jan['sales']

diff_sales

Store_A    200.0
Store_B      NaN
Store_C    300.0
Name: sales, dtype: float64

In [20]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0)

sales_feb_aligned

         sales
Store_A    400
Store_B      0
Store_C    600

In [21]:
diff_sales = sales_feb_aligned['sales'] - sales_jan['sales']

diff_sales

Store_A    200
Store_B   -400
Store_C    300
Name: sales, dtype: int64

In [30]:
dff = pd.Series([1,2,3,4,5], name="numbers")
dff

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: int64

In [32]:
stock_a = pd.DataFrame({'Price': [12, 45, 46], 
                        'Stock': [30,10,5],
                        'Product': ['Phone', 'Laptop','Watch']})

stock_a

   Price  Stock Product
0     12     30   Phone
1     45     10  Laptop
2     46      5   Watch

In [33]:
stock_b = pd.DataFrame({'Price': [10, 50, 46], 
                        
                        'Product': ['Phone', 'Laptop','Watch']})

stock_b

   Price Product
0     10   Phone
1     50  Laptop
2     46   Watch

In [34]:
diff_stock = stock_b['Stock'] - stock_a['Stock']

diff_stock

KeyError: 'Stock'

In [36]:
align_stock_b = stock_b.reindex(columns=stock_a.columns, fill_value=0)

align_stock_b

   Price  Stock Product
0     10      0   Phone
1     50      0  Laptop
2     46      0   Watch

In [38]:
diff_stock = align_stock_b['Stock'] - stock_a['Stock']

diff_stock

0   -30
1   -10
2    -5
Name: Stock, dtype: int64

##Better way Vectorize / Apply

In [6]:
df['Category_vectorized'] = df['Age'].apply(lambda age : 'Young' if age < 40 else 'Adult')

In [8]:
df['Category_vectorized'][:10]

0    Young
1    Young
2    Young
3    Young
4    Young
5    Adult
6    Adult
7    Young
8    Young
9    Young
Name: Category_vectorized, dtype: str

In [12]:
caterized_check_lamda = lambda age : 'Young' if age < 40  else "Adult"
df['Category_vectorized_2'] = df['Age'].apply(caterized_check_lamda)
df['Category_vectorized_2'].head(10)

0    Young
1    Young
2    Young
3    Young
4    Young
5    Adult
6    Adult
7    Young
8    Young
9    Young
Name: Category_vectorized_2, dtype: str

In [ ]:
def check_if_age_is_young(age):
    # if age < 40:
    #     return 'Young'
    # else :
    #     return 'Adult'
    return 'Young' if age < 40 else 'Adult'
df['Category_vectorized_3'] = df['Age'].apply(check_if_age_is_young)
df['Category_vectorized_3'].head(10)

0    Young
1    Young
2    Young
3    Young
4    Young
5    Adult
6    Adult
7    Young
8    Young
9    Young
Name: Category_vectorized_3, dtype: str

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Category_vectorized,Category_vectorized_2,Category_vectorized_3
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Young,Young,Young
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Young,Young,Young
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Young,Young,Young
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Young,Young,Young
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Young,Young,Young

In [50]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Category_vectorized',
       'Category_vectorized_2', 'Category_vectorized_3',
       'Categorize_age_Survived'],
      dtype='str')

In [57]:
def check_age_Survived(row):
    print(row)
    age = row['Age']
    survived = row['Survived']
    if survived == '1' :
        if age < 40:
            return 'Young'
        else:
            return 'Seniors'
    else:
        return 'Dead'

        df['Categorize_age_Survived']= df['Age', 'Survived' ].apply(check_age_Survived, axis=1)
        df['Categorize_age_Survived']

In [37]:
df[['Age', 'Survived' ]].head()

    Age  Survived
0  22.0         0
1  38.0         1
2  26.0         1
3  35.0         1
4  35.0         0

In [58]:
df['Categorize_age_Survived']= df.apply(check_age_Survived)
df['Categorize_age_Survived'].head()

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

KeyError: 'Age'

In [13]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [14]:
start = df.loc[1, 'Name'].find("(")

In [15]:
end = df.loc[1, 'Name'].find(")")

In [16]:
df.loc[1, 'Name'][0: start] + df.loc[1, 'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [19]:
def remove_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [26]:
df['Name_trimmed'] = df['Name'].apply(remove_substring)

In [27]:
df['Name_trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

In [23]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [28]:
df.loc[1, 'Name_trimmed']

'Cumings, Mrs. John Bradley'

In [ ]:

df['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: str

In [ ]:
df['Category_vectorized'] = df['Age'].apply(lambda age : 'Young' if age < 40 else 'Adult')

In [30]:
df['sex_encode'] = df['Sex'].apply(lambda sex : 1 if sex == 'male' else 0 )

In [31]:
df['sex_encode'].head()

0    1
1    0
2    0
3    0
4    1
Name: sex_encode, dtype: int64

In [ ]:
#===================================================